spring.application.name=AWS FILE SHARE

aws.region=ap-south-1
aws.s3.bucketName=fileshare-alfaj-project

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.enabled=true
spring.thymeleaf.check-template-location=true